version: '3'
services:
  api:
    restart: always
    image: express-api
    build: api/
    networks:
      - backend
    depends_on:
      - db
    ports:
    - "3000:3000"
  
  db:
    restart: always
    image: mysql-bdd
    build: bdd/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: masterdle
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - backend
  
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - backend
    depends_on:
      - db

volumes:
  db-volume:

networks:
  backend:
    driver: bridge